language: node_js
sudo: false
node_js:
  - 0.12
  - 4
  - 5
  - 6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
    - clang
before_script:
  - npm install -g gulp-cli
  - npm install -g snyk
after_script:
  - npm run coverage